# Generated by Django 3.1.1 on 2020-09-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_date',
            new_name='date_created',
        ),
    ]
